server.port=8080

# langchain4j.open-ai.chat-model.api-key=demo
# langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

langchain4j.google-ai-gemini.chat-model.api-key=AQ.Ab8RN6KEAD2VhRDFaJp3daqmt27KfQCqQvnV_b0WyF2Gd2OOVw
langchain4j.google-ai-gemini.chat.model.log-requests=true
langchain4j.google-ai-gemini.chat.model.log-responses=true

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/tempo_db
spring.datasource.username=canuto
spring.datasource.password=H4lf8l00d
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect