spring.application.name=tempo

# langchain4j.open-ai.chat-model.api-key=demo
# langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

langchain4j.google-ai-gemini.chat-model.api-key=AQ.Ab8RN6KEAD2VhRDFaJp3daqmt27KfQCqQvnV_b0WyF2Gd2OOVw
langchain4j.google-ai-gemini.chat-model.model-name=gemini-3.8-flash
